# Generated by Django 5.2.3 on 2025-06-18 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnosis_App', '0003_labbasicinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostictest',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='components',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='interpretations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='measures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='reports_within',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TestFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, null=True)),
                ('answer', models.TextField(null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='Diagnosis_App.diagnostictest')),
            ],
        ),
    ]
