# Generated by Django 5.2.3 on 2025-06-19 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnosis_App', '0005_branch_delete_labbasicinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostictest',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Diagnosis_App.branch'),
        ),
        migrations.AddField(
            model_name='testpackage',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Diagnosis_App.branch'),
        ),
    ]
