# Generated by Django 5.2.3 on 2025-06-21 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnosis_App', '0006_diagnostictest_branch_testpackage_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('report_time', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fasting_required', models.BooleanField(default=False)),
                ('sample_type', models.CharField(max_length=100)),
                ('target_audience', models.CharField(blank=True, max_length=200, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Diagnosis_App.branch')),
                ('tests', models.ManyToManyField(blank=True, to='Diagnosis_App.diagnostictest')),
            ],
        ),
    ]
