# Generated by Django 5.2.3 on 2025-07-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnosis_App', '0011_order_result_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkup',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
