# Generated by Django 5.2.3 on 2025-07-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnosis_App', '0012_checkup_views_diagnostictest_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location_url',
            field=models.URLField(null=True),
        ),
    ]
