# Generated by Django 5.2.3 on 2025-07-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnosis_App', '0014_branch_latitude_branch_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
