# Generated by Django 5.2.3 on 2025-07-31 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnosis_App', '0015_branch_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_Selected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Diagnosis_App.branch')),
            ],
        ),
    ]
